name: finnish_media_scrapers
channels:
  - conda-forge
dependencies:
  - python=3
  - selenium
  - beautifulsoup4
  - requests
  - lxml
  - autopep8
  - pre-commit
  - pylint
  - pandas
  - geckodriver
